import assert from 'node:assert/strict'
import {execFile} from 'node:child_process'
import {readFile} from 'node:fs/promises'
import test from 'node:test'
import {promisify} from 'node:util'

const execFileAsync = promisify(execFile)

test('front-end app script is syntactically valid JavaScript', async () => {
	await execFileAsync(process.execPath, ['--check', 'public/app.js'])
})

test('front-end skill icons do not override DK actions with ACR icon assets', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.equal(appSource.includes('PixelHotkeysV4_BigCutePinkOrange'), false)
	assert.equal(appSource.includes('/resources/acr-packages/'), false)
	assert.equal(appSource.includes('/kano-source/Resources/'), false)
	assert.equal(appSource.includes('iconMap'), false)
	assert.match(appSource, /function renderIcon\([^)]*explicitUrl/)
	assert.match(appSource, /src="\$\{explicitUrl\}"/)
})

test('timeline action labels use real action names while preserving original timeline text', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /function displayNameForAction\(/)
	assert.match(appSource, /ACTION_LABELS\.get\(actionId\)/)
	assert.match(appSource, /timelineLabel:\s*event\.timelineLabel \|\| \(label !== event\.name \? event\.name : ''\)/)
	assert.match(appSource, /原轴：/)
	assert.match(appSource, /timelineLabel \? `原轴：\$\{timelineLabel\}` : ''/)
})

test('front-end renders mitigation, healing and DoT timeline items as duration bars', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function coverageItemType\(/)
	assert.match(appSource, /event\.classification === 'mitigation'/)
	assert.match(appSource, /event\.classification === 'healing'/)
	assert.match(appSource, /function isDotTimelineEvent\(/)
	assert.match(appSource, /classification === 'dot'/)
	assert.match(appSource, /item\.type === `dot`/)
	assert.match(appSource, /type:\s*'dot'/)
	assert.match(appSource, /id:\s*'mitigation-actions'/)
	assert.match(appSource, /label:\s*'减伤 \/ 奶轴'/)
	assert.match(css, /\.xiva-item\.mitigation\s*\{/)
	assert.match(css, /\.xiva-item\.healing\s*\{/)
	assert.match(css, /\.xiva-item\.dot\s*\{/)
})

test('mitigation phase rows dedupe imported duplicate actions by action and time', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /function uniqueTimelineDisplayEvents\(/)
	assert.match(appSource, /function timelineDisplayEventKey\(/)
	assert.match(appSource, /function uniqueDetailDisplayEvents\(/)
	assert.match(appSource, /function detailDisplayEventKey\(/)
	assert.match(appSource, /return sortTimelineItems\(uniqueTimelineDisplayEvents\(\[\.\.\.mitigationItems, \.\.\.qtItems, \.\.\.manualItems\]\)\)/)
	assert.match(appSource, /return uniqueDetailDisplayEvents\(detailEventsForCurrentPhase\(uniqueDetailEvents\(/)
	assert.match(appSource, /event\.manualId \? `manual:\$\{event\.manualId\}`/)
	assert.match(appSource, /Math\.round\(Number\(event\.timeMs \?\? event\.startMs \?\? 0\)\)/)
})

test('front-end filters phase rows before applying visible item limits', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /function limitVisibleTimelineRowItems\(/)
	assert.match(appSource, /const simulated = state\.showAcrSimulation\s*\?\s*\(track\.simulated \?\? state\.model\.acrSimulation\?\.events \?\? \[\]\)\s*:\s*\[\]/)
	assert.doesNotMatch(appSource, /track\.simulated \?\? state\.model\.acrSimulation\?\.events \?\? \[\]\)\.slice\(0,\s*420\)/)
	assert.match(appSource, /timelineRowsForPhase\(rows, state\.model\.bossTimeline\?\.source, state\.phase\)\s*\.map\(limitVisibleTimelineRowItems\)/)
	assert.match(appSource, /phaseStartMs:\s*event\.phaseStartMs/)
})

test('imported non-DRK timelines receive current job ACR simulation fallback', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /function buildAcrSimulationForImportedJob\(/)
	assert.match(appSource, /const acrSimulation = buildAcrSimulationForImportedJob\(imported\)/)
	assert.match(appSource, /model\.acrSimulation = acrSimulation/)
	assert.match(appSource, /model\.tracks\.expert\.simulated = acrSimulation\.events/)
	assert.match(appSource, /action\.job === imported\.jobId/)
	assert.match(appSource, /source:\s*`\$\{imported\.acrName\} ACR`/)
	assert.match(appSource, /simulated:\s*true/)
	assert.match(appSource, /classification:\s*'damage'/)
	assert.match(appSource, /output:\s*true/)
	assert.doesNotMatch(appSource, /imported\.jobId === 'DRK' && state\.baseAcrSimulation/)
	assert.doesNotMatch(appSource, /events:\s*\[\]\}/)
})

test('front-end exposes editor workflow controls without overflowing panels', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /showFocusPicker/)
	assert.match(appSource, /renderFocusSkillModal\(/)
	assert.match(appSource, /data-action="open-focus-picker"/)
	assert.equal(appSource.includes('focus-picker-row'), false)
	assert.match(appSource, /state\.editorMode/)
	assert.match(appSource, /data-toggle="editor-mode"/)
	assert.match(appSource, /draggable="\$\{draggable \? 'true' : 'false'\}"/)
	assert.match(appSource, /renderAcrModal\(/)
	assert.match(appSource, /data-action="open-acr-database"/)
	assert.match(appSource, /data-action="import-timeline"/)
	assert.match(appSource, /data-action="export-timeline"/)
	assert.match(appSource, /type="file"[^>]*data-field="timeline-import"/)
	assert.match(appSource, /renderBurstGroupsInDetailPanel\(/)
	assert.match(css, /\.panel-tabs\s*\{[^}]*flex-wrap:\s*wrap/s)
	assert.match(css, /\.panel-tabs\s*\{[^}]*grid-template-columns/s)
	assert.match(css, /\.modal-backdrop\s*\{/)
	assert.match(css, /\.acr-dock\s*\{[^}]*width:\s*auto/s)
	assert.equal(appSource.includes('完整时间轴、爆发整合、技能插入和关注技能放在同一个工作台'), false)
	assert.equal(appSource.includes('<p class="eyebrow">统一编辑器</p>'), false)
})

test('share preview labels use the current timeline name instead of the mode name', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /model\.shareCard\.timelineName/)
	assert.match(appSource, /timelineName:\s*imported\.name/)
	assert.doesNotMatch(appSource, /<p class="eyebrow">个人展示模式<\/p>/)
	assert.doesNotMatch(appSource, /title:\s*`\$\{imported\.name\} 分享预览`/)
})

test('tools are integrated into the main editor instead of fixed side rails', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')
	const renderBody = appSource.match(/function render\(\) \{[\s\S]*?\n\}/)?.[0] ?? ''

	assert.doesNotMatch(renderBody, /renderSidebar\(/)
	assert.doesNotMatch(renderBody, /renderInspector\(/)
	assert.match(renderBody, /state\.section === 'tools' \? renderToolPanel\(model\) : renderUnifiedEditor\(model\)/)
	assert.match(appSource, /function renderCompactNav\(/)
	assert.match(appSource, /function renderToolPanel\(/)
	assert.match(appSource, /section:\s*'timeline'/)
	assert.match(appSource, /data-section="tools"/)
	assert.match(appSource, /data-section="timeline"/)
	assert.match(appSource, /<p class="eyebrow">工具<\/p>/)
	assert.match(css, /\.app-shell\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)/s)
	assert.match(css, /\.tool-grid\s*\{[^}]*grid-template-columns:/s)
	assert.match(css, /\.compact-nav\s*\{/)
})

test('tools panel keeps FFLogs comparison and removes placeholder import source cards', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')
	const modelSource = await readFile('src/app-model.mjs', 'utf8')
	const prototype = await readFile('public/data/prototype.json', 'utf8')

	assert.match(appSource, /function renderFflogsComparisonPanel\(/)
	assert.match(appSource, /renderFflogsComparisonPanel\(model\)/)
	assert.doesNotMatch(appSource, /model\.importSources/)
	assert.doesNotMatch(appSource, /白轴存储/)
	assert.doesNotMatch(appSource, /class="white-shaft"/)
	assert.doesNotMatch(appSource, /class="source-row"/)
	assert.doesNotMatch(css, /\.white-shaft/)
	assert.doesNotMatch(css, /\.source-row/)
	assert.doesNotMatch(modelSource, /importSources/)
	assert.doesNotMatch(prototype, /"importSources"/)
})

test('FFLogs comparison sends the full current player axis to the server', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function renderFflogsComparisonPanel\(/)
	assert.match(appSource, /function loadFflogsComparison\(/)
	assert.match(appSource, /function fflogsComparisonEvents\(/)
	assert.match(appSource, /function renderDamageAdjustmentBreakdown\(/)
	assert.match(appSource, /data-action="load-fflogs-comparison"/)
	assert.match(appSource, /data-action="apply-log-gcd-utilization"/)
	assert.match(appSource, /data-action="reset-gcd-utilization"/)
	assert.match(appSource, /data-field="fflogs-actor"/)
	assert.match(appSource, /data-field="fflogs-gcd-utilization"/)
	assert.match(appSource, /simulatedEvents:\s*fflogsComparisonEvents\(\)/)
	assert.match(appSource, /targetGcdUtilizationPercent:\s*Number\(state\.fflogsTargetGcdUtilization\)/)
	assert.match(appSource, /function renderGcdUtilizationControl\(/)
	assert.match(appSource, /function setFflogsTargetGcdUtilization\(/)
	assert.match(appSource, /renderCompareMetric\([^)]*renderDamageAdjustmentBreakdown\(comparison\)/)
	assert.match(appSource, /renderCompareMetric\([^)]*renderGcdUtilizationControl\(comparison\)/)
	assert.match(appSource, /function fflogsCurrentSimulationEvents\(/)
	assert.match(appSource, /function fflogsCurrentTimelineEvents\(/)
	assert.match(appSource, /return uniqueComparisonEvents\(\[\s*\.\.\.fflogsCurrentSimulationEvents\(\),\s*\.\.\.fflogsCurrentTimelineEvents\(\),\s*\.\.\.manualQueueEvents\(\),\s*\]\)/)
	assert.doesNotMatch(appSource, /simulatedEvents:\s*\[\.\.\.\(state\.model\.damage\.events/)
	assert.match(css, /\.fflogs-panel\s*\{/)
	assert.match(css, /\.fflogs-metric-grid\s*\{/)
	assert.match(css, /\.gcd-utilization-control\s*\{/)
	assert.match(css, /\.compare-table\s*\{/)
})

test('timeline editor mode clearly separates browse and edit interactions', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /editorMode:\s*'browse'/)
	assert.equal(appSource.includes("localStorage.getItem('webtimelineEditorMode')"), false)
	assert.equal(appSource.includes("localStorage.setItem('webtimelineEditorMode'"), false)
	assert.match(appSource, /function canEditTimeline\(/)
	assert.equal(appSource.includes('function renderEditorModeStatus('), false)
	assert.match(appSource, /state\.editorMode === 'edit' \? '编辑模式' : '浏览模式'/)
	assert.match(appSource, /function isDraggableSkillCard\(/)
	assert.match(appSource, /event\.sidebarType !== 'acr'/)
	assert.match(appSource, /data-skill-source="\$\{event\.sidebarType\}"/)
	assert.match(appSource, /ACR 自动技能已锁定/)
	assert.match(appSource, /data-manual-id="\$\{item\.manualId\}"/)
	assert.match(appSource, /data-timeline-event-key="\$\{item\.editableEventKey\}"/)
	assert.match(appSource, /function canEditTimelineItem\(/)
	assert.match(appSource, /function timelineEventEditKey\(/)
	assert.match(appSource, /function moveExistingTimelineEventAtTimeline\(/)
	assert.match(appSource, /function editableTimelineEventTargets\(/)
	assert.match(appSource, /for \(const target of targets\) \{/)
	assert.match(appSource, /updateTimelineEventPosition\(target\.event, dropInfo\)/)
	assert.match(appSource, /event\.dataTransfer\.setData\('application\/x-webtimeline-event'/)
	assert.match(appSource, /data-action="remove-manual-skill"/)
	assert.match(appSource, /moveManualSkillAtTimeline\(/)
	assert.match(appSource, /event\.dataTransfer\.setData\('application\/x-webtimeline-manual'/)
	assert.match(appSource, /dataTransferHasType\(dataTransfer, 'application\/x-webtimeline-event'\)/)
	assert.match(appSource, /dataTransferHasType\(event\.dataTransfer, 'application\/x-webtimeline-event'\) \? 'move' : 'copy'/)
	assert.match(appSource, /if \(!canEditTimeline\(\)\) \{/)
	assert.equal(css.includes('.editor-mode-status'), false)
	assert.match(css, /\.xiva-item\.editable-manual\.editable\s*\{/)
	assert.match(css, /\.xiva-item\.editable-timeline-event\.editable\s*\{/)
	assert.match(css, /\.manual-remove\s*\{/)
	assert.match(css, /\.skill-card\.acr-locked\s*\{/)
})

test('insert skill panel is a movable floating editor-only palette', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function renderInsertFloat\(/)
	assert.match(appSource, /if \(!canEditTimeline\(\) \|\| state\.section !== 'timeline'\)/)
	assert.match(appSource, /data-insert-float-handle="true"/)
	assert.match(appSource, /programming-mode-button\.jpg/)
	assert.match(appSource, /class="insert-float-avatar"/)
	assert.match(appSource, /class="insert-float-state"/)
	assert.match(appSource, /function startInsertFloatDrag\(/)
	assert.match(appSource, /function moveInsertFloat\(/)
	assert.match(appSource, /function insertFloatPlacement\(/)
	assert.match(appSource, /has-drawer/)
	assert.match(appSource, /align-right/)
	assert.match(appSource, /align-up/)
	assert.match(appSource, /webtimelineInsertFloatPos/)
	assert.match(appSource, /function insertSkillGroups\(/)
	assert.equal(appSource.includes('INSERT_SKILL_PANEL_LIMIT'), false)
	assert.match(appSource, /function insertSkillAtVisibleTimeline\(/)
	assert.match(appSource, /data-action="quick-insert-skill"/)
	assert.match(appSource, /data-insert-panel-handle="true"/)
	assert.match(appSource, /id:\s*'all'/)
	assert.match(appSource, /id:\s*'output',\s*label:\s*'输出'/)
	assert.match(appSource, /id:\s*'mitigation',\s*label:\s*'减伤'/)
	assert.match(appSource, /id:\s*'potion',\s*label:\s*'爆发药'/)
	assert.match(appSource, /\{id:\s*'burst',\s*label:\s*'[^']+',\s*skills:\s*burstGroups\}/)
	assert.doesNotMatch(appSource, /id:\s*'burst60'/)
	assert.doesNotMatch(appSource, /id:\s*'burst120'/)
	assert.match(appSource, /data-drag-skill="\$\{event\.actionId\}"/)
	assert.match(css, /\.insert-float\s*\{[^}]*position:\s*fixed/s)
	assert.match(css, /\.insert-float\.has-drawer\s*\{/)
	assert.match(css, /\.insert-float\.align-right\s*\{/)
	assert.match(css, /\.insert-float\.align-up\s*\{/)
	assert.match(css, /\.insert-float-button\s*\{[^}]*border-radius:\s*999px/s)
	assert.match(css, /\.insert-float-avatar\s*\{[^}]*object-fit:\s*cover/s)
	assert.match(css, /\.insert-float-state\s*\{[^}]*position:\s*absolute/s)
	assert.match(css, /\.floating-skill-drawer\s*\{[^}]*max-height:/s)
	assert.match(css, /\.insert-category-tabs\s*\{/)
})

test('insert skill palette wraps skills into multiple rows and supports native drag drop types', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(css, /\.skill-strip\s*\{[^}]*display:\s*grid/s)
	assert.match(css, /\.skill-strip\s*\{[^}]*grid-template-columns:\s*repeat\(auto-fill,\s*minmax\(176px,\s*1fr\)\)/s)
	assert.match(css, /\.skill-strip\s*\{[^}]*overflow-y:\s*auto/s)
	assert.doesNotMatch(css, /\.skill-strip\s*\{[^}]*overflow-x:\s*auto/s)
	assert.match(css, /\.skill-card\s*\{[^}]*min-width:\s*0/s)
	assert.match(appSource, /function dataTransferHasType\(/)
	assert.match(appSource, /Array\.from\(dataTransfer\?\.types \?\? \[\]\)/)
	assert.match(appSource, /dataTransferHasType\(event\.dataTransfer,\s*'application\/x-webtimeline-manual'\)/)
	assert.doesNotMatch(appSource, /event\.dataTransfer\.types\.includes/)
}
)

test('insert skill palette has pointer drag fallback for dropping skills on the timeline', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /let insertSkillDrag = null/)
	assert.match(appSource, /function startInsertSkillDrag\(/)
	assert.match(appSource, /function moveInsertSkillDrag\(/)
	assert.match(appSource, /function endInsertSkillDrag\(/)
	assert.match(appSource, /function insertSkillAtClientPoint\(/)
	assert.match(appSource, /function insertQtAtClientPoint\(/)
	assert.match(appSource, /function dropTimeInfoForClientPoint\(/)
	assert.match(appSource, /function renderDropTimePreview\(/)
	assert.match(appSource, /function findTimelineAtClientPoint\(/)
	assert.match(appSource, /document\.querySelectorAll\('\.xiva-timeline'\)/)
	assert.match(appSource, /findTimelineAtClientPoint\(event\.clientX,\s*event\.clientY\)/)
	assert.match(appSource, /const actionId = insertSkillDrag\.actionId/)
	assert.match(appSource, /const qtIndex = insertSkillDrag\.qtIndex/)
	assert.match(appSource, /insertSkillAtClientPoint\(actionId,\s*event\.clientX,\s*event\.clientY\)/)
	assert.match(appSource, /insertQtAtClientPoint\(qtIndex,\s*event\.clientX,\s*event\.clientY\)/)
	assert.match(appSource, /absoluteMsForPhaseTime\(state\.model\.bossTimeline\?\.source,\s*state\.phase,\s*phaseTimeMs\)/)
	assert.match(appSource, /phaseLabelForTime\(state\.model\.bossTimeline\?\.source,\s*state\.phase,\s*phaseTimeMs\)/)
	assert.match(appSource, /insertSkillDrag\.ghost\.innerHTML = renderDropTimePreview/)
	assert.match(css, /\.skill-drag-ghost\s*\{/)
	assert.match(css, /\.skill-drag-ghost-time\s*\{/)
	assert.match(css, /\.skill-drag-ghost-phase\s*\{/)
	assert.match(css, /\.skill-card\.is-pointer-dragging\s*\{/)
	assert.match(css, /\.xiva-timeline\.is-skill-drop-target\s*\{/)
})

test('insert skill palette offers built-in FF14 combat potions by level', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /potionAttribute:\s*'strength'/)
	assert.match(appSource, /const POTION_ATTRIBUTES = \[/)
	assert.match(appSource, /id:\s*'intelligence',\s*label:\s*'智力'/)
	assert.match(appSource, /id:\s*'dexterity',\s*label:\s*'巧力'/)
	assert.match(appSource, /const COMBAT_POTION_TIERS = \[/)
	assert.match(appSource, /Grade 2 Gemdraught/)
	assert.match(appSource, /Grade 8 Tincture/)
	assert.match(appSource, /function potionInsertItems\(/)
	assert.match(appSource, /\{id:\s*'potion',\s*label:\s*'爆发药',\s*skills:\s*potionInsertItems\(\)\}/)
	assert.match(appSource, /function renderPotionInsertPanel\(/)
	assert.match(appSource, /function renderPotionInsertCard\(/)
	assert.match(appSource, /function renderPotionTimelineIcon\(/)
	assert.match(appSource, /function activePotionAttribute\(/)
	assert.match(appSource, /function setPotionAttribute\(/)
	assert.match(appSource, /data-potion-attribute="\$\{attribute\.id\}"/)
	assert.match(appSource, /potionAttributeLabel\(event\.attributeId\)/)
	assert.match(appSource, /name:\s*`\$\{tier\.label\}\$\{attribute\.label\}药`/)
	assert.match(appSource, /data-action="quick-insert-potion"/)
	assert.match(appSource, /data-drag-potion="\$\{event\.potionId\}"/)
	assert.match(appSource, /application\/x-webtimeline-potion/)
	assert.match(appSource, /item\.type === 'potion'[\s\S]*return renderPotionTimelineIcon\(item\)/)
	assert.match(appSource, /function insertPotionAtMs\(/)
	assert.match(appSource, /kind:\s*'potion'/)
	assert.match(appSource, /classification:\s*'potion'/)
	assert.match(appSource, /recastMs:\s*270000/)
	assert.match(appSource, /durationMs:\s*30000/)
	assert.match(appSource, /function hasMeaningfulCdAdjustment\(/)
	assert.match(appSource, /Number\(event\.cdAdjustedMs \?\? 0\) >= 1000/)
	assert.match(appSource, /const adjustedByCooldown = adjusted >= 1000/)
	assert.match(appSource, /hasMeaningfulCdAdjustment\(item\) \? `队列CD调整/)
	assert.match(appSource, /hasMeaningfulCdAdjustment\(event\) \? `队列已顺延/)
	assert.match(css, /\.insert-potion-panel\s*\{/)
	assert.match(css, /\.potion-attribute-grid\s*\{/)
	assert.match(css, /\.potion-attribute-card\.active\s*\{/)
	assert.match(css, /\.potion-insert-card\s*\{/)
	assert.match(css, /\.potion-tier-pill\s*\{/)
	assert.match(css, /\.skill-icon\.potion-timeline-icon\s*\{/)
})

test('timeline drag guide shows drop bubble and nearest event delta while editing', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /renderTimelineDragGuide\(\)/)
	assert.match(appSource, /class="timeline-drag-guide"/)
	assert.match(appSource, /function showTimelineDragGuide\(/)
	assert.match(appSource, /function hideTimelineDragGuide\(/)
	assert.match(appSource, /function nearestTimelineGuideEvent\(/)
	assert.match(appSource, /function timelineGuideEvents\(/)
	assert.match(appSource, /function renderTimelineGuideDelta\(/)
	assert.match(appSource, /scheduleTimelineDragGuide\(timeline, event\.clientX\)/)
	assert.match(appSource, /hideTimelineDragGuide\(timeline\)/)
	assert.match(appSource, /timeline\.dataset\.guideVisible = 'true'/)
	assert.match(appSource, /timeline\.style\.setProperty\('--guide-left'/)
	assert.match(appSource, /timeline\.style\.setProperty\('--guide-delta-left'/)
	assert.match(css, /\.timeline-drag-guide\s*\{/)
	assert.match(css, /\.timeline-drag-guide-bubble\s*\{/)
	assert.match(css, /\.timeline-drag-guide-delta\s*\{/)
	assert.match(css, /\.xiva-timeline\[data-guide-visible="true"\]\s+\.timeline-drag-guide\s*\{/)
})

test('timeline drag guide schedules high frequency updates through RAF and cached context', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /let timelineDragGuideFrame = null/)
	assert.match(appSource, /let timelineDragGuidePending = null/)
	assert.match(appSource, /let timelineDragGuideCache = null/)
	assert.match(appSource, /function scheduleTimelineDragGuide\(/)
	assert.match(appSource, /function flushTimelineDragGuide\(/)
	assert.match(appSource, /function timelineDragGuideContext\(/)
	assert.match(appSource, /function nearestTimelineGuideEventFromCache\(/)
	assert.match(appSource, /requestAnimationFrame\(flushTimelineDragGuide\)/)
	assert.match(appSource, /cancelAnimationFrame\(timelineDragGuideFrame\)/)
	assert.match(appSource, /scheduleTimelineDragGuide\(timeline, event\.clientX\)/)
	assert.match(appSource, /dropTimeInfoForClientPoint\(event\.clientX,\s*event\.clientY,\s*timelineDragGuideContext\(timeline\)\)/)
	assert.match(appSource, /function dropTimeInfoForClientPoint\(clientX, clientY, context = null\)/)
	assert.match(appSource, /const timeline = context\?\.timeline \?\? findTimelineAtClientPoint\(clientX, clientY\)/)
	assert.doesNotMatch(appSource, /showTimelineDragGuide\(timeline, event\.clientX\)/)
	assert.match(css, /will-change:\s*transform/)
	assert.match(css, /translate3d\(var\(--guide-left/)
}
)

test('timeline drag guide uses the track content origin so dropped skills align with the guide line', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /trackContentLeft/)
	assert.match(appSource, /trackContentLeft:\s*\(axisRect\?\.left \?\? rect\.left\) - rect\.left \+ timeline\.scrollLeft/)
	assert.match(appSource, /const trackX = Math\.max\(0,\s*clientX - context\.trackLeft\)/)
	assert.match(appSource, /const guideLeftPx = context\.trackContentLeft \+ trackX/)
	assert.match(appSource, /containerLeft:\s*context\?\.trackLeft \?\? rect\.left/)
	assert.match(appSource, /scrollLeft:\s*context \? 0 : timeline\.scrollLeft/)
	assert.match(appSource, /scrollWidth:\s*context\?\.trackWidth \?\? timeline\.scrollWidth/)
	assert.doesNotMatch(appSource, /clientX - context\.trackLeft \+ timeline\.scrollLeft/)
}
)

test('burst insert drawer offers only draggable 60 and 120 burst package buttons', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')
	const detailSource = appSource.slice(appSource.indexOf('function renderBurstGroupsInDetailPanel('), appSource.indexOf('function renderFocusSkillModal('))
	const drawerSource = appSource.slice(appSource.indexOf('function renderSkillDrawer('), appSource.indexOf('function insertSkillGroups('))
	const rowsSource = appSource.slice(appSource.indexOf('function buildVisualTimelineRows('), appSource.indexOf('function buildOutputLaneItems('))
	const burstPanelSource = appSource.slice(appSource.indexOf('function renderBurstInsertPanel('), appSource.indexOf('function insertSkillGroups('))

	assert.match(appSource, /\{id:\s*'burst',\s*label:\s*'爆发'\}/)
	assert.match(rowsSource, /id:\s*'burst-integration',\s*label:\s*'爆发'/)
	assert.doesNotMatch(appSource, /label:\s*'爆发整合'/)
	assert.doesNotMatch(appSource, /label:\s*'60 \/ 120 爆发整合'/)
	const tabIndex = drawerSource.indexOf('class="insert-category-tabs"')
	const topPanelIndex = drawerSource.indexOf('class="insert-burst-panel"')
	assert.ok(tabIndex >= 0)
	assert.ok(topPanelIndex === -1 || topPanelIndex > tabIndex)
	assert.match(drawerSource, /activeGroup\.id === 'burst' \? renderBurstInsertPanel\(activeGroup\.skills\)/)
	assert.match(appSource, /function renderBurstInsertPanel\(bursts\)/)
	assert.match(appSource, /function uniqueBurstInsertChoices\(bursts\)/)
	assert.match(appSource, /const choices = uniqueBurstInsertChoices\(bursts\)/)
	assert.match(appSource, /choices\.map\(renderBurstInsertCard\)/)
	assert.match(appSource, /window === '60s'/)
	assert.match(appSource, /window === '120s'/)
	assert.doesNotMatch(burstPanelSource, /renderBurstPlanner\(/)
	assert.doesNotMatch(burstPanelSource, /type="range"/)
	assert.match(appSource, /draggable="true"[^>]*data-drag-burst="\$\{event\.burstIndex\}"/)
	assert.match(appSource, /data-burst-index="\$\{burstId\}"/)
	assert.match(appSource, /application\/x-webtimeline-burst/)
	assert.match(appSource, /function insertBurstPackageAtTimeline\(/)
	assert.match(appSource, /function insertBurstPackageAtMs\(/)
	assert.doesNotMatch(detailSource, /renderBurstPlanner\(/)
	assert.doesNotMatch(detailSource, /input type="range"/)
	assert.match(appSource, /\{id:\s*'burst',\s*label:\s*'[^']+',\s*skills:\s*burstGroups\}/)
	assert.doesNotMatch(appSource, /id:\s*'burst60'/)
	assert.doesNotMatch(appSource, /id:\s*'burst120'/)
	assert.match(css, /\.insert-burst-panel\s*\{/)
	assert.match(css, /\.insert-burst-card-grid\s*\{/)
	assert.match(css, /\.burst-insert-card\s*\{/)
	assert.doesNotMatch(css, /\.insert-burst-planner input\[type="range"\]/)
})

test('insert skill palette is current-job only with burst package categories', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /data-insert-panel-handle="true"/)
	assert.match(appSource, /function currentJobInsertSkills\(/)
	assert.match(appSource, /skill\.job === state\.job/)
	const insertSkillFunction = appSource.slice(appSource.indexOf('function currentJobInsertSkills('), appSource.indexOf('function isCurrentJobInsertEvent('))
	assert.equal(insertSkillFunction.includes("skill.job === 'ROLE'"), false)
	assert.match(appSource, /id:\s*'all'/)
	assert.match(appSource, /id:\s*'output'/)
	assert.match(appSource, /id:\s*'mitigation'/)
	assert.match(appSource, /id:\s*'potion'/)
	assert.match(appSource, /id:\s*'qt'/)
	assert.match(appSource, /qtDraftStates:\s*\{\}/)
	assert.match(appSource, /function insertQtControls\(/)
	assert.match(appSource, /function qtStatePanelItems\(/)
	assert.match(appSource, /qtStates:\s*\[\{Name:\s*name,\s*Enabled:\s*enabled\}\]/)
	assert.match(appSource, /function renderQtInsertCard\(/)
	assert.match(appSource, /function renderQtGamePanel\(/)
	assert.match(appSource, /function renderQtDraftPanel\(/)
	assert.match(appSource, /function toggleQtDraftState\(/)
	assert.match(appSource, /function insertQtDraftAtVisibleTimeline\(/)
	assert.match(appSource, /activeGroup\.id === 'qt' \? renderQtGamePanel\(activeGroup\.skills\)/)
	assert.match(appSource, /class="qt-panel-note"/)
	assert.match(appSource, /class="qt-game-panel"/)
	assert.match(appSource, /class="qt-game-grid"/)
	assert.match(appSource, /class="qt-draft-panel"/)
	assert.match(appSource, /class="qt-draft-logic"/)
	assert.match(appSource, /class="qt-game-toggle \$\{qtDraftEnabledFor\(event\) \? 'is-on' : 'is-off'\}/)
	assert.match(appSource, /data-action="toggle-qt-draft"/)
	assert.match(appSource, /data-action="insert-qt-draft"/)
	assert.match(appSource, /data-drag-qt="\$\{event\.qtIndex\}"/)
	assert.match(appSource, /data-qt-enabled="\$\{qtDraftEnabledFor\(event\) \? 'true' : 'false'\}"/)
	assert.match(appSource, /application\/x-webtimeline-qt/)
	assert.match(appSource, /function insertQtAtVisibleTimeline\(/)
	assert.match(appSource, /Type:\s*'BatchTriggerQt'/)
	assert.match(appSource, /QtStates:\s*item\.qtStates/)
	assert.match(appSource, /\{id:\s*'burst',\s*label:\s*'[^']+',\s*skills:\s*burstGroups\}/)
	assert.doesNotMatch(appSource, /id:\s*'burst60'/)
	assert.doesNotMatch(appSource, /id:\s*'burst120'/)
	assert.match(appSource, /function uniqueBurstInsertChoices\(/)
	assert.match(appSource, /data-action="quick-insert-burst"/)
	assert.match(appSource, /data-drag-burst="\$\{event\.burstIndex\}"/)
	assert.equal(appSource.includes("id: 'utility'"), false)
	assert.equal(appSource.includes("id: 'healing'"), false)
	assert.match(appSource, /function isInsertOutputOverride\(/)
	assert.match(appSource, /function renderBurstInsertCard\(/)
	assert.match(css, /\.floating-skill-drawer \.section-heading\s*\{[^}]*cursor:\s*grab/s)
	assert.match(css, /\.qt-panel-note\s*\{/)
	assert.match(css, /\.qt-insert-card\s*\{/)
	assert.match(css, /\.qt-game-panel\s*\{/)
	assert.match(css, /\.qt-game-grid\s*\{[^}]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/s)
	assert.match(css, /\.qt-draft-panel\s*\{/)
	assert.match(css, /\.qt-draft-logic\s*\{/)
	assert.match(css, /\.qt-game-toggle\.is-on\s*\{/)
	assert.match(css, /\.qt-game-toggle\.is-off\s*\{/)
	assert.doesNotMatch(css, /#d66491/)
	assert.doesNotMatch(css, /rgba\(255,\s*160,\s*176/)
})

test('insert skill id entry is compact and auto-matches action names', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function insertIdPreviewName\(/)
	assert.match(appSource, /data-field="skill-id"/)
	assert.match(appSource, /data-insert-id-preview/)
	assert.equal(appSource.includes('data-field="skill-name"'), false)
	assert.equal(appSource.includes('技能名，可留空'), false)
	assert.match(appSource, /const name = action\?\.name \?\? `技能 \$\{id\}`/)
	assert.match(css, /\.floating-skill-drawer\s*\{[^}]*width:\s*min\(900px,\s*calc\(100vw - 24px\)\)/s)
	assert.match(css, /\.insert-float\.has-drawer\s*\{[^}]*width:\s*min\(900px,\s*calc\(100vw - 24px\)\)/s)
	assert.match(css, /\.insert-row\s*\{[^}]*grid-template-columns:\s*minmax\(120px,\s*180px\)\s+minmax\(140px,\s*1fr\)\s+auto/s)
})

test('inserted skills stay manual instead of becoming focused skills', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	const insertFunction = appSource.slice(appSource.indexOf('function insertSkillAtMs('), appSource.indexOf('function moveManualSkillAtTimeline('))
	assert.equal(insertFunction.includes('addFocusedSkill'), false)
	assert.match(appSource, /data-action="quick-insert-skill" data-drag-skill="\$\{event\.actionId\}"/)
	assert.doesNotMatch(appSource, /<button type="button" data-focus-skill="\$\{event\.actionId\}" title="显示这个技能的位置">\+<\/button>/)
})

test('manual insert queue applies cooldown checks and marks shifted events', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function normalizeManualQueue\(/)
	assert.match(appSource, /manualCooldownKey\(/)
	assert.match(appSource, /manualActionQueueLockMs\(/)
	assert.match(appSource, /requestedTimeMs/)
	assert.match(appSource, /cdAdjustedMs/)
	assert.match(appSource, /队列CD调整/)
	assert.match(appSource, /队列已顺延/)
	assert.match(css, /\.manual-cd-badge\s*\{/)
})

test('main timeline uses functional editor lanes instead of source-based rows', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const buildRows = appSource.slice(appSource.indexOf('function buildVisualTimelineRows('), appSource.indexOf('function limitVisibleTimelineRowItems('))

	assert.match(buildRows, /id:\s*'output-actions'/)
	assert.match(buildRows, /label:\s*'\u8f93\u51fa\u8f74'/)
	assert.match(buildRows, /id:\s*'mitigation-actions'/)
	assert.match(buildRows, /label:\s*'\u51cf\u4f24 \/ \u5976\u8f74'/)
	assert.match(buildRows, /id:\s*'burst-integration'/)
	assert.match(buildRows, /label:\s*'\u7206\u53d1'/)
	assert.doesNotMatch(buildRows, /label:\s*'\u7206\u53d1\u6574\u5408'/)
	assert.match(buildRows, /id:\s*'acr-simulated',\s*label:\s*'ACR \u6a21\u62df'/)
	assert.doesNotMatch(buildRows, /label:\s*'KANO ACR \u6a21\u62df'/)
	assert.match(appSource, /function buildOutputLaneItems\(/)
	assert.match(appSource, /function buildBurstLaneItems\(/)
	assert.match(appSource, /function buildMitigationLaneItems\(/)
	assert.doesNotMatch(buildRows, /label:\s*'GCD \/ Actions'/)
	assert.doesNotMatch(buildRows, /label:\s*'QT \/ Potion'/)
	assert.doesNotMatch(buildRows, /label:\s*'Manual Insert'/)
})

test('timeline drops only accept skills in their matching functional lane', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const rowSource = appSource.slice(appSource.indexOf('function renderTimelineRow('), appSource.indexOf('function renderTimelineRowLabel('))
	const skillDropSource = appSource.slice(appSource.indexOf('function insertSkillAtTimeline('), appSource.indexOf('function insertSkillAtVisibleTimeline('))
	const skillPointerSource = appSource.slice(appSource.indexOf('function insertSkillAtClientPoint('), appSource.indexOf('function insertSkillAtVisibleTimeline('))
	const burstDropSource = appSource.slice(appSource.indexOf('function insertBurstPackageAtTimeline('), appSource.indexOf('function insertBurstPackageAtMs('))
	const burstPointerSource = appSource.slice(appSource.indexOf('function insertBurstPackageAtClientPoint('), appSource.indexOf('function insertBurstPackageAtMs('))

	assert.match(rowSource, /data-row-id="\$\{row\.id\}"/)
	assert.match(rowSource, /data-drop-lane="\$\{timelineDropLaneForRow\(row\)\}"/)
	assert.match(appSource, /function timelineDropLaneForRow\(/)
	assert.match(appSource, /function timelineDropLaneForTarget\(/)
	assert.match(appSource, /function timelineDropLaneAtClientPoint\(/)
	assert.match(appSource, /function actionTimelineDropLane\(/)
	assert.match(appSource, /function canDropActionOnTimelineLane\(/)
	assert.match(appSource, /function canDropBurstPackageOnTimelineLane\(/)
	assert.match(appSource, /row\.id === 'output-actions'\)\s*return 'output'/)
	assert.match(appSource, /row\.id === 'mitigation-actions'\)\s*return 'mitigation'/)
	assert.match(appSource, /row\.id === 'burst-integration'\)\s*return 'burst'/)
	assert.match(appSource, /dropLane === 'locked'/)
	assert.match(skillDropSource, /const dropLane = timelineDropLaneForTarget\(event\.target\)/)
	assert.match(skillDropSource, /if \(!canDropActionOnTimelineLane\(actionId, dropLane\)\)/)
	assert.match(skillPointerSource, /const dropLane = timelineDropLaneAtClientPoint\(clientX, clientY\)/)
	assert.match(burstDropSource, /if \(!canDropBurstPackageOnTimelineLane\(dropLane\)\)/)
	assert.match(burstPointerSource, /const dropLane = timelineDropLaneAtClientPoint\(clientX, clientY\)/)
	assert.match(burstPointerSource, /if \(!canDropBurstPackageOnTimelineLane\(dropLane\)\)/)
})

test('manual insert queue checks cooldowns against existing timeline events before shifting skills', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /function timelineCooldownBaselineEvents\(/)
	assert.match(appSource, /function normalizeManualQueue\(events = \[\], baselineEvents = timelineCooldownBaselineEvents\(\)\)/)
	assert.match(appSource, /isManual:\s*false/)
	assert.match(appSource, /isManual:\s*true/)
	assert.match(appSource, /applyCooldownUsage\(/)
	assert.match(appSource, /Math\.max\(actualTimeMs,\s*Number\(nextReadyByKey\.get\(cooldownKey\) \?\? 0\)\)/)
	assert.match(appSource, /manualTimelineItemType\(/)
	assert.match(appSource, /if \(item\.manualId\)/)
})

test('manual inserted skills use boss target for output and require user targets for mitigation', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')
	const insertFunction = appSource.slice(appSource.indexOf('function insertSkillAtMs('), appSource.indexOf('function manualInsertStatusTime('))
	const manualEditorSource = appSource.slice(appSource.indexOf('function renderManualEditorRow('), appSource.indexOf('function manualEventsForPanel('))
	const exportSource = appSource.slice(appSource.indexOf('function buildExportTimelineFromState('), appSource.indexOf('function jobFromTimelineMeta('))

	assert.match(appSource, /function defaultManualTargetForAction\(/)
	assert.match(appSource, /function requiresManualTargetChoice\(/)
	assert.match(insertFunction, /target:\s*defaultManualTargetForAction\(action,\s*classification\.type\)/)
	assert.match(insertFunction, /targetRequired:\s*requiresManualTargetChoice\(action,\s*classification\.type\)/)
	assert.doesNotMatch(manualEditorSource, /renderManualTargetControl\(event,\s*canEdit\)/)
	assert.match(exportSource, /Target:\s*exportTargetForEvent\(item\)/)
	assert.match(appSource, /function exportTargetForEvent\(/)
	assert.match(appSource, /if \(isOutputTimelineEvent\(event\) && !event\.target\) \{\s*return 'Target'\s*\}/s)
	assert.match(css, /\.detail-target-field\s*\{/)
	assert.match(css, /\.target-required-warning\s*\{/)
})

test('mitigation detail panel edits targets for imported and manual coverage skills', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')
	const changeSource = appSource.slice(appSource.indexOf("document.addEventListener('change'"), appSource.indexOf('function render()'))
	const detailRowSource = appSource.slice(appSource.indexOf('function renderDetailEventRow('), appSource.indexOf('function renderManualEditor('))
	const importSource = appSource.slice(appSource.indexOf('function importExportedEvents('), appSource.indexOf('function importedEventDurationMs('))
	const flattenSource = appSource.slice(appSource.indexOf('function flattenImportedTimeline('), appSource.indexOf('function buildImportedModeTracks('))

	assert.match(detailRowSource, /renderDetailTargetControl\(panel,\s*event,\s*index,\s*canEditTarget\)/)
	assert.match(appSource, /function canEditDetailTarget\(/)
	assert.match(appSource, /function renderDetailTargetControl\(/)
	assert.match(appSource, /data-detail-target="\$\{detailEditKey\(panel,\s*event,\s*index\)\}"/)
	assert.match(changeSource, /const detailTarget = event\.target\.closest\('\[data-detail-target\]'\)/)
	assert.match(changeSource, /updateDetailEventTarget\(detailTarget\.dataset\.detailTarget,\s*detailTarget\.value\)/)
	assert.match(appSource, /function updateDetailEventTarget\(/)
	assert.match(appSource, /const target = editableDetailEventTarget\(detailKey\)/)
	assert.match(appSource, /target\.event\.target = String\(value \?\? ''\)/)
	assert.match(importSource, /const targetRequired = Boolean\(event\.targetRequired \?\? requiresManualTargetChoice\(action,\s*classification\)\)/)
	assert.match(importSource, /targetRequired,\s*\n/)
	assert.match(flattenSource, /targetRequired:\s*requiresManualTargetChoice\(actionRecord,\s*classification\.type\)/)
	assert.match(css, /\.detail-target-field\s*\{/)
})

test('60 and 120 burst packages participate in the main timeline preview', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function buildBurstPackageItems\(/)
	assert.match(appSource, /id:\s*'burst-integration'/)
	assert.match(appSource, /type:\s*'burst-package'/)
	assert.match(appSource, /60 爆发包/)
	assert.match(appSource, /120 爆发包/)
	assert.match(appSource, /skillCount:\s*burstSkillCount\(burst\)/)
	assert.match(appSource, /sourceLabel:\s*burstSourceLabel\(burst\)/)
	assert.match(appSource, /item\.type === 'burst-package'/)
	assert.match(css, /\.xiva-item\.burst-package\s*\{/)
	assert.match(css, /\.burst-package-source\s*\{/)
})

test('burst package timeline bubbles display the judged drop time explicitly', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')
	const itemSource = appSource.slice(appSource.indexOf('function renderTimelineItem('), appSource.indexOf('function renderTimelineSourceBadge('))
	const insertSource = appSource.slice(appSource.indexOf('function insertBurstPackageAtMs('), appSource.indexOf('function insertSkillAtMs('))

	assert.match(itemSource, /class="burst-package-time"/)
	assert.match(itemSource, /判定 \$\{burstPackageTimeLabel\(item,\s*startTimeLabel\)\}/)
	assert.match(itemSource, /burstPackageAbsoluteLabel\(item\)/)
	assert.match(appSource, /function burstPackageTimeLabel\(/)
	assert.match(appSource, /function burstPackageAbsoluteLabel\(/)
	assert.match(insertSource, /timeMs,\s*\n\s*requestedTimeMs:\s*timeMs/)
	assert.match(insertSource, /phaseStartMs:\s*phaseInfo\.phaseId === 'all' \? undefined : Number\(phaseInfo\.absoluteTimeMs \?\? timeMs\) - Number\(phaseInfo\.phaseTimeMs \?\? 0\)/)
	assert.match(css, /\.burst-package-time\s*\{/)
	assert.match(css, /\.burst-package-absolute\s*\{/)
	assert.match(css, /\.xiva-item\.burst-package\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto;/s)
	assert.doesNotMatch(css, /\.xiva-item\.burst-package\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto\s+auto;/s)
})

test('manual burst packages stay draggable and obey 60 or 120 second cooldown windows', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')
	const itemSource = appSource.slice(appSource.indexOf('function renderTimelineItem('), appSource.indexOf('function renderTimelineSourceBadge('))
	const queueSource = appSource.slice(appSource.indexOf('function normalizeManualQueue('), appSource.indexOf('function nextManualReadyTime('))
	const readySource = appSource.slice(appSource.indexOf('function nextManualReadyTime('), appSource.indexOf('function baselineConflictsWithManual('))
	const cooldownKeySource = appSource.slice(appSource.indexOf('function manualCooldownKey('), appSource.indexOf('function manualActionRecastMs('))
	const recastSource = appSource.slice(appSource.indexOf('function manualActionRecastMs('), appSource.indexOf('function manualActionQueueLockMs('))
	const baselineSource = appSource.slice(appSource.indexOf('function timelineCooldownBaselineEvents('), appSource.indexOf('function applyCooldownUsage('))
	const insertSource = appSource.slice(appSource.indexOf('function insertBurstPackageAtMs('), appSource.indexOf('function insertSkillAtMs('))

	assert.match(itemSource, /const editableBurstPackage = canEditTimeline\(\) && Boolean\(item\.manualId\)/)
	assert.match(itemSource, /data-manual-id="\$\{item\.manualId\}"/)
	assert.match(itemSource, /draggable="\$\{editableBurstPackage \? 'true' : 'false'\}"/)
	assert.match(itemSource, /burst-package-adjusted/)
	assert.match(cooldownKeySource, /event\.type === 'burst-package'/)
	assert.match(cooldownKeySource, /`burst-package:\$\{event\.window \?\? '60s'\}`/)
	assert.match(recastSource, /event\.type === 'burst-package'/)
	assert.match(recastSource, /event\.window === '120s' \? 120000 : 60000/)
	assert.match(readySource, /if \(event\.type === 'burst-package'\)/)
	assert.match(readySource, /return cooldownKey && recastMs > 0\s*\?\s*Math\.max\(requestedTimeMs,\s*Number\(nextReadyByKey\.get\(cooldownKey\) \?\? 0\)\)\s*:\s*requestedTimeMs/s)
	assert.match(baselineSource, /buildBurstPackageItems\(track\.burst \?\? state\.model\.tracks\.beginner\?\.burst \?\? \[\]\)/)
	assert.match(queueSource, /manualCooldownKey\(event,\s*action\)/)
	assert.match(insertSource, /const inserted = state\.inserted\.find\(item => item\.id === manualId\)/)
	assert.match(insertSource, /已顺延到/)
	assert.match(css, /\.burst-package-adjusted\s*\{/)
	assert.match(css, /\.xiva-item\.burst-package\.editable\s*\{/)
}
)

test('QT timeline controls render a visible fallback icon', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')
	const itemSource = appSource.slice(appSource.indexOf('function renderTimelineItem('), appSource.indexOf('function renderTimelineSourceBadge('))

	assert.match(appSource, /function renderTimelineIcon\(/)
	assert.match(itemSource, /renderTimelineIcon\(item,\s*itemLabel\)/)
	assert.match(appSource, /item\.kind === 'qt-control'/)
	assert.match(appSource, /class="skill-icon fallback qt-fallback"/)
	assert.match(css, /\.xiva-item\.action span\.skill-icon/)
	assert.match(css, /\.skill-icon\.qt-fallback\s*\{/)
	assert.match(css, /\.xiva-item \.skill-icon\.qt-fallback\s*\{[^}]*background:/s)
})

test('timeline import exposes visible status and errors instead of failing silently', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /importStatus:\s*''/)
	assert.match(appSource, /importError:\s*''/)
	assert.match(appSource, /function renderImportFeedback\(/)
	assert.match(appSource, /class="import-feedback/)
	assert.match(appSource, /try\s*\{/)
	assert.match(appSource, /catch \(error\)/)
	assert.match(appSource, /setImportError\(/)
	assert.match(appSource, /setImportStatus\(/)
	assert.match(css, /\.import-feedback\s*\{/)
	assert.match(css, /\.import-feedback\.error\s*\{/)
})

test('timeline export writes a stable round-trippable WebTimeline schema', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /schemaVersion:\s*1/)
	assert.match(appSource, /meta:\s*\{/)
	assert.match(appSource, /phases:\s*exportPhaseWindows\(/)
	assert.match(appSource, /boss:\s*exportBossTimeline\(/)
	assert.match(appSource, /player:\s*exportPlayerTimeline\(/)
	assert.match(appSource, /burstPackages:\s*buildBurstPackageItems\(/)
	assert.match(appSource, /qt:\s*exportQtControls\(/)
	assert.match(appSource, /opener:\s*exportOpenerEvents\(/)
	assert.match(appSource, /focusedSkills:\s*\[\.\.\.state\.focusedSkills\]/)
	assert.match(appSource, /categories:\s*exportTimelineCategories\(/)
	assert.match(appSource, /manual:\s*state\.inserted\.map/)
	assert.match(appSource, /timelineJson\.schemaVersion === 1/)
})

test('timeline import restores action durations from the skill database when exports omit them', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /function importedEventDurationMs\(/)
	assert.match(appSource, /importedEventDurationMs\(event,\s*action,\s*fallbackKind\)/)
	assert.match(appSource, /Number\(action\?\.effectDurationMs \?\? 0\)/)
	assert.match(appSource, /event\.castDurationMs \?\? durationMs/)
	assert.doesNotMatch(appSource, /const durationMs = Number\(event\.durationMs \?\? 0\)\s*\n\s*return \{/)
})

test('PR timeline import uses the shared parser for parallel branches and boss cast sync', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /flattenPrTimeline/)
	assert.match(appSource, /collectBossCastItems/)
	assert.match(appSource, /resolveBossCastConditionTimeMs/)
	assert.match(appSource, /resolveConditionTimeMs:\s*\(condition,\s*cursorMs\)/)
	assert.doesNotMatch(appSource, /let cursorMs = 0[\s\S]*?function flattenImportedTimeline/)
})

test('focus skill control is clickable from the row label and keeps empty tracked rows visible', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /function renderFocusAddLabel\(/)
	assert.match(appSource, /data-action="open-focus-picker"/)
	assert.match(appSource, /keepWhenEmpty:\s*true/)
	assert.match(appSource, /data-action="remove-focused-skill"/)
})

test('focus skill tracker renders every occurrence with icon, time and source labels', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function focusTrackerItemForEvent\(/)
	assert.match(appSource, /function focusSourceLabel\(/)
	assert.match(appSource, /function uniqueFocusEvents\(/)
	assert.match(appSource, /function focusEventKey\(/)
	assert.match(appSource, /uniqueFocusEvents\(\[/)
	assert.match(appSource, /focus-tracker-item/)
	assert.match(appSource, /focus-tracker-source/)
	assert.match(appSource, /ACR 自动/)
	assert.match(appSource, /用户手动/)
	assert.match(appSource, /导入时间轴/)
	assert.match(appSource, /type:\s*'focus-tracker'/)
	assert.match(appSource, /sourceLabel:\s*focusSourceLabel\(event\)/)
	assert.match(css, /\.xiva-item\.focus-tracker\s*\{/)
	assert.match(css, /\.focus-tracker-source\s*\{/)
})

test('focus skill tracker uses the selected skill name and exposes all current job skills', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /label:\s*skill\?\.name\s*\?\?\s*event\.name/)
	assert.match(appSource, /eventLabel:\s*event\.name/)
	assert.equal(appSource.includes('.slice(0, 96)'), false)
	assert.equal(appSource.includes("String(event?.id ?? event?.name ?? '')"), false)
})

test('P1 focus control is presented as a skill tracker instead of a plain follow list', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /技能追踪器/)
	assert.match(appSource, /追踪当前职业的任意技能/)
	assert.match(appSource, /placeholder="搜索技能名或技能 ID"/)
	assert.match(appSource, /显示出现次数、时间点和来源/)
	assert.match(css, /\.focus-tracker-help\s*\{/)
})

test('focus skill picker separates current job skills from collapsed other skills', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function groupedFocusCandidates\(/)
	assert.match(appSource, /function isCurrentJobFocusSkill\(/)
	assert.doesNotMatch(appSource, /function focusCandidatesForCurrentJob\(/)
	assert.match(appSource, /const timelineActionIds = new Set/)
	assert.match(appSource, /isCurrentJobFocusSkill\(skill\) && timelineActionIds\.has\(String\(skill\.id\)\)/)
	assert.match(appSource, /当前职业技能/)
	assert.match(appSource, /其他技能/)
	assert.match(appSource, /<details class="focus-skill-section other-skills"/)
	assert.match(appSource, /id:\s*'current-job'/)
	assert.match(appSource, /renderFocusSkillGrid\(groups\.other,\s*'other-skills'\)/)
	assert.match(appSource, /data-focus-section="\$\{id\}"/)
	assert.match(css, /\.focus-skill-section\s*\{/)
	assert.match(css, /\.focus-skill-section\.other-skills\s*>\s*summary\s*\{/)
	assert.match(css, /\.focus-skill-section-heading\s*\{/)
})

test('P1 ACR database modal shows status, author, source and placeholders for every job', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function acrSupportStatus\(/)
	assert.match(appSource, /function renderAcrStatusBadge\(/)
	assert.match(appSource, /function renderAcrField\(/)
	assert.match(appSource, /function publicAcrSourceLabel\(/)
	assert.match(appSource, /已支持/)
	assert.match(appSource, /未支持/)
	assert.match(appSource, /等待接入/)
	assert.match(appSource, /作者：/)
	assert.match(appSource, /数据来源：/)
	assert.match(appSource, /数据来源：',\s*publicAcrSourceLabel\(primaryAcr\?\.source \?\? model\.skillDatabase\?\.source\?\.name\)/)
	assert.match(appSource, /title="\$\{publicAcrSourceLabel\(acr\.source\)\}"/)
	assert.match(appSource, /<small>\$\{publicAcrSourceLabel\(acr\.source\)\}<\/small>/)
	assert.match(appSource, /支持状态：/)
	assert.match(css, /\.acr-status\s*\{/)
	assert.match(css, /\.acr-status\.supported\s*\{/)
	assert.match(css, /\.acr-status\.unsupported\s*\{/)
	assert.match(css, /\.acr-status\.waiting\s*\{/)
})

test('P1 job and ACR selectors expose current state and unknown fallbacks', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function renderJobAcrStatus\(/)
	assert.match(appSource, /当前选择/)
	assert.match(appSource, /职业：/)
	assert.match(appSource, /ACR：/)
	assert.match(appSource, /unknown/)
	assert.match(appSource, /未指定/)
	assert.match(appSource, /等待接入/)
	assert.match(css, /\.job-acr-status\s*\{/)
	assert.match(css, /\.job-acr-status \.current\s*\{/)
})

test('P1 boss cast cards expose cast, release, end, damage and high damage state', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /highDamageClass/)
	assert.match(appSource, /noDamageClass/)
	assert.match(appSource, /cast-start/)
	assert.match(appSource, /释放判定/)
	assert.match(appSource, /结束/)
	assert.match(appSource, /formatDamage\(damage\)/)
	assert.match(css, /\.xiva-item\.cast\.high-damage\s*\{/)
	assert.match(css, /\.xiva-item\.cast\.no-damage\s*\{/)
	assert.match(css, /\.cast-start\s*\{/)
})

test('P1 boss damage cards keep name, resolve time and damage readable', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /if \(isDamage\) \{/)
	assert.match(appSource, /boss-damage-card/)
	assert.match(appSource, /boss-damage-name/)
	assert.match(appSource, /boss-damage-meta/)
	assert.match(appSource, /boss-damage-time/)
	assert.match(appSource, /boss-damage-value/)
	assert.match(appSource, /判定 \$\{startTimeLabel\}/)
	assert.match(css, /\.xiva-item\.damage\.boss-damage-card\s*\{/)
	assert.match(css, /\.boss-damage-name\s*\{/)
	assert.match(css, /\.boss-damage-meta\s*\{/)
	assert.match(css, /\.boss-damage-time\s*\{/)
	assert.match(css, /\.boss-damage-value\s*\{/)
	assert.match(css, /min-width:\s*148px/)
})

test('P1 boss cast and damage cards share lane spacing to avoid global phase overlap', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /const bossLaneTop = `calc\(7px \+ \$\{lane\} \* 62px\)`/)
	assert.match(appSource, /class="xiva-item cast [^"]+" style="left:\$\{start\}%; top:\$\{bossLaneTop\};/)
	assert.match(appSource, /class="xiva-item damage boss-damage-card" style="left:\$\{start\}%; top:\$\{bossLaneTop\};/)
	assert.doesNotMatch(appSource, /top:calc\(7px \+ \$\{lane\} \* 58px\)/)
	assert.doesNotMatch(appSource, /top:calc\(7px \+ \$\{lane\} \* 46px\)/)
})

test('P1 timeline skill source badges use consistent labels and colors', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function sourceClassForTimelineItem\(/)
	assert.match(appSource, /function sourceLabelForTimelineItem\(/)
	assert.match(appSource, /source-badge/)
	assert.match(appSource, /data-source-kind="\$\{sourceKind\}"/)
	assert.match(appSource, /ACR 自动/)
	assert.match(appSource, /用户手动/)
	assert.match(appSource, /导入时间轴/)
	assert.match(appSource, /爆发药/)
	assert.match(appSource, /减伤/)
	assert.match(appSource, /治疗/)
	assert.match(css, /\.source-badge\s*\{/)
	assert.match(css, /\.xiva-item\.source-acr\s+\.source-badge\s*\{/)
	assert.match(css, /\.xiva-item\.source-manual\s+\.source-badge\s*\{/)
	assert.match(css, /\.xiva-item\.source-import\s+\.source-badge\s*\{/)
	assert.match(css, /\.xiva-item\.source-mitigation\s+\.source-badge\s*\{/)
	assert.match(css, /\.xiva-item\.source-healing\s+\.source-badge\s*\{/)
	assert.match(css, /\.xiva-item\.source-potion\s+\.source-badge\s*\{/)
})

test('P2 detail panel exposes a full-page overview across timeline sections', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /id:\s*'overview'/)
	assert.match(appSource, /label:\s*'整页总览'/)
	assert.match(appSource, /function renderOverviewPanel\(/)
	assert.match(appSource, /function overviewSections\(/)
	assert.match(appSource, /Boss 读条/)
	assert.match(appSource, /减伤 \/ 奶轴/)
	assert.match(appSource, /输出轴/)
	assert.match(appSource, /爆发药轴/)
	assert.match(appSource, /起手/)
	assert.match(appSource, /overview-section/)
	assert.match(appSource, /overview-count/)
	assert.match(css, /\.overview-grid\s*\{/)
	assert.match(css, /\.overview-grid\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)/s)
	assert.match(css, /\.overview-section\s*\{/)
	assert.match(css, /\.overview-count\s*\{/)
})

test('P2 detail rows track skills without copy-to-manual clutter', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')
	const detailRowSource = appSource.slice(appSource.indexOf('function renderDetailEventRow('), appSource.indexOf('function renderManualEditor('))

	assert.match(appSource, /function renderDetailEventRow\(/)
	assert.doesNotMatch(appSource, /copyDetailEventToManual|data-action="copy-detail-event"|复制到手动轴/)
	assert.match(appSource, /const timelineEventKey = detailTimelineEventKey\(event\)/)
	assert.match(appSource, /data-action="locate-timeline-event"/)
	assert.match(appSource, /data-timeline-event-key="\$\{timelineEventKey\}"/)
	assert.doesNotMatch(detailRowSource, /data-focus-skill|isFocused|focused-detail-row/)
	assert.match(appSource, /function detailFocusActionId\(/)
	assert.match(appSource, /actionByName\(eventName\)/)
	assert.match(css, /\.detail-actions\s*\{/)
	assert.match(css, /\.detail-meta\s*\{/)
	assert.match(css, /\.detail-count-badge\s*\{/)
})

test('P2 focus picker tracking preserves the opened detail collapse', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /openDetailCollapses:\s*\[\]/)
	assert.match(appSource, /function rememberOpenDetailCollapses\(/)
	assert.match(appSource, /function isDetailCollapseOpen\(/)
	assert.match(appSource, /document\.addEventListener\('toggle'/)
	assert.match(appSource, /rememberOpenDetailCollapses\(\)\s*\n\t\taddFocusedSkill\(target\.dataset\.focusSkill\)/)
	assert.match(appSource, /open:\s*isDetailCollapseOpen\(panel\.id\)/)
	assert.match(appSource, /open:\s*isDetailCollapseOpen\(`overview-\$\{section\.id\}`\)/)
	assert.match(appSource, /open:\s*isDetailCollapseOpen\('burst'\)/)
})

test('detail row trace jumps to the matching timeline item without adding a focused skill', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')
	const clickSource = appSource.slice(appSource.indexOf("document.addEventListener('click'"), appSource.indexOf("document.addEventListener('change'"))
	const detailRowSource = appSource.slice(appSource.indexOf('function renderDetailEventRow('), appSource.indexOf('function renderManualEditor('))
	const timelineItemSource = appSource.slice(appSource.indexOf('function renderTimelineItem('), appSource.indexOf('function renderTimelineSourceBadge('))

	assert.match(clickSource, /if \(action === 'locate-timeline-event'\)/)
	assert.match(clickSource, /locateTimelineEvent\(target\.dataset\.timelineEventKey\)/)
	assert.doesNotMatch(detailRowSource, /state\.focusedSkills\.includes\(String\(focusActionId\)\)/)
	assert.match(detailRowSource, /data-action="locate-timeline-event"/)
	assert.match(detailRowSource, /data-timeline-event-key="\$\{timelineEventKey\}"/)
	assert.match(detailRowSource, /class="mini-button"/)
	assert.doesNotMatch(detailRowSource, /trace-button/)
	assert.match(detailRowSource, />追踪<\/button>|>杩借釜<\/button>/)
	assert.match(timelineItemSource, /data-locate-event-key="\$\{item\.locateEventKey\}"/)
	assert.match(appSource, /function locateTimelineEvent\(/)
	assert.match(appSource, /function flashTimelineElement\(/)
	assert.match(appSource, /timeline-locate-flash/)
	assert.match(css, /\.xiva-item\.timeline-locate-flash\s*\{[^}]*z-index:\s*30/s)
	assert.match(css, /@keyframes timelineLocateFlash[\s\S]*outline:\s*3px solid #111827/)
	assert.match(css, /@keyframes timelineLocateFlash[\s\S]*box-shadow:[^;]*rgba\(17,\s*24,\s*39/)
	assert.doesNotMatch(css, /\.detail-actions \.trace-button/)
})

test('P2 manual timeline events can be edited from the detail panel', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function renderManualEditor\(/)
	assert.match(appSource, /function updateManualSkillTime\(/)
	assert.match(appSource, /function duplicateManualSkill\(/)
	assert.match(appSource, /data-manual-time="\$\{event\.id\}"/)
	assert.match(appSource, /data-action="nudge-manual-skill"/)
	assert.match(appSource, /data-action="duplicate-manual-skill"/)
	assert.match(appSource, /data-action="remove-manual-skill"/)
	assert.match(appSource, /手动轴编辑/)
	assert.match(css, /\.manual-editor\s*\{/)
	assert.match(css, /\.manual-edit-row\s*\{/)
	assert.match(css, /\.manual-time-field\s*\{/)
})

test('P2 detail panel collapses sections and reuses the output simulation switch', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(appSource, /function renderDetailCollapse\(/)
	assert.match(appSource, /function detailPanelEvents\(/)
	assert.match(appSource, /function outputDetailEvents\(/)
	assert.match(appSource, /data-toggle="acr-simulation"/)
	assert.match(appSource, /state\.showAcrSimulation\s*\?\s*'隐藏 ACR 模拟'\s*:\s*'显示 ACR 模拟'/)
	assert.match(appSource, /<details class="detail-collapse/)
	assert.match(appSource, /detail-expanded-list/)
	assert.doesNotMatch(appSource, /detail-preview-list|renderDetailPreviewRow|DETAIL_COLLAPSED_LIMIT/)
	assert.match(css, /\.detail-collapse\s*\{/)
	assert.match(css, /\.detail-sim-toggle\s*\{/)
})

test('P2 right detail column is wider and collapsed cards show text only', async () => {
	const css = await readFile('public/styles.css', 'utf8')
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(css, /\.unified-grid\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+clamp\(380px,\s*30vw,\s*440px\)/s)
	assert.match(css, /\.detail-collapse:not\(\[open\]\)\s+\.detail-sim-toggle\s*,\s*\n\.detail-collapse:not\(\[open\]\)\s+\.detail-expanded-list\s*\{[^}]*display:\s*none/s)
	assert.match(css, /\.detail-collapse\[open\]\s*>\s*summary\s+\.detail-sim-toggle\s*\{[^}]*display:\s*none/s)
	assert.match(css, /@media \(max-width:\s*1120px\)\s*\{[\s\S]*?\.unified-grid\s*\{[\s\S]*?grid-template-columns:\s*1fr/s)
	assert.match(css, /\.detail-expanded-list\s*\{[^}]*max-height:\s*min\(420px,\s*58vh\)/s)
	assert.match(css, /\.detail-row\s*\{[^}]*grid-template-columns:\s*24px\s+minmax\(0,\s*1fr\)\s+minmax\(54px,\s*68px\)\s+auto/s)
	assert.match(css, /\.detail-row\.has-target-detail-row\s*\{[^}]*grid-template-columns:\s*24px\s+minmax\(0,\s*1fr\)\s+minmax\(54px,\s*68px\)\s+minmax\(104px,\s*128px\)\s+auto/s)
	assert.match(css, /\.detail-actions\s*\{[^}]*justify-content:\s*flex-end/s)
	assert.doesNotMatch(css, /\.detail-actions\s*\{[^}]*grid-column:\s*2\s*\/\s*-1/s)
	assert.match(css, /\.detail-row \.skill-icon\s*\{[^}]*width:\s*24px/s)
	const renderDetailCollapseSource = appSource.slice(
		appSource.indexOf('function renderDetailCollapse'),
		appSource.indexOf('function renderOutputSimulationControl'),
	)
	assert.doesNotMatch(renderDetailCollapseSource, /<summary>[\s\S]*?\$\{controls\}[\s\S]*?<\/summary>/)
	assert.match(appSource, /<div class="detail-expanded-list">\s*\$\{controls\}\s*\$\{expandedBody\}/s)
	assert.match(appSource, /has-target-detail-row/)
})

test('P2 detail panel filters and edits manual events inside the active phase', async () => {
	const appSource = await readFile('public/app.js', 'utf8')

	assert.match(appSource, /function detailEventsForCurrentPhase\(/)
	assert.match(appSource, /function phaseRelativeMsForEvent\(/)
	assert.match(appSource, /function currentPhaseEditWindow\(/)
	assert.match(appSource, /function clampMsToCurrentPhase\(/)
	assert.match(appSource, /function updateDetailEventTime\(/)
	assert.match(appSource, /data-detail-time="\$\{detailEditKey\(panel, event, index\)\}"/)
	assert.match(appSource, /function detailEditKey\(/)
	assert.match(appSource, /function editableDetailEventTarget\(/)
	assert.match(appSource, /updateDetailEventTime\(detailTimeTarget\.dataset\.detailTime,\s*detailTimeTarget\.value\)/)
	assert.match(appSource, /absoluteMsForPhaseTime\(state\.model\.bossTimeline\?\.source,\s*state\.phase,\s*phaseTimeMs\)/)
	assert.match(appSource, /target\.event\.timeMs = clamped\.absoluteTimeMs/)
	assert.match(appSource, /target\.event\.phase = clamped\.phaseId === 'all' \? 'global' : clamped\.phaseId\.toUpperCase\(\)/)
})

test('right detail panel has a dedicated editable QT tab', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const tabsSource = appSource.slice(appSource.indexOf('function renderPanelTabs('), appSource.indexOf('function renderDetailPanel('))
	const detailPanelSource = appSource.slice(appSource.indexOf('function renderDetailPanel('), appSource.indexOf('function detailPanelEvents('))
	const burstPanelSource = appSource.slice(appSource.indexOf('function renderBurstGroupsInDetailPanel('), appSource.indexOf('function renderQtDetailPanel('))
	const detailTargetSource = appSource.slice(appSource.indexOf('function editableDetailEventTarget('), appSource.indexOf('function nudgeManualSkill('))

	assert.match(tabsSource, /\{id:\s*'qt',\s*label:\s*'QT'\}/)
	assert.match(detailPanelSource, /if \(state\.panel === 'qt'\)/)
	assert.match(detailPanelSource, /return renderQtDetailPanel\(\)/)
	assert.match(appSource, /function renderQtDetailPanel\(/)
	assert.match(appSource, /function qtDetailEvents\(/)
	assert.match(appSource, /function editableQtEvents\(/)
	assert.match(appSource, /function normalizeEditableQtEvent\(/)
	assert.match(appSource, /const qtEvents = editableQtEvents\(\)/)
	assert.match(appSource, /\(state\.model\.tracks\.expert\.qt \?\? \[\]\)\.map\(normalizeEditableQtEvent\)/)
	assert.match(appSource, /manualEventsForPanel\('qt'\)\.map\(detailManualEvent\)/)
	assert.match(appSource, /const panel = virtualDetailPanel\('qt',\s*'QT 控制',\s*events\)/)
	assert.match(burstPanelSource, /const burstEvents = detailEventsForCurrentPhase\(buildBurstPackageItems\(bursts\)\)/)
	assert.doesNotMatch(burstPanelSource, /timelineQtEvents/)
	assert.match(burstPanelSource, /renderDetailEventRow\(panel,\s*event,\s*index\)/)
	assert.match(appSource, /function virtualDetailPanel\(/)
	assert.match(appSource, /function resolveDetailPanelById\(/)
	assert.match(detailTargetSource, /const panel = resolveDetailPanelById\(panelId\)/)
	assert.match(appSource, /if \(panelId === 'qt'\)/)
	assert.match(appSource, /return virtualDetailPanel\('qt',\s*'QT 控制',\s*qtDetailEvents\(\)\)/)
	assert.match(appSource, /target\.event\.endMs = clamped\.absoluteTimeMs \+ durationMs/)
})

test('QT detail rows can be tracked and editable timeline events can be deleted from cards', async () => {
	const appSource = await readFile('public/app.js', 'utf8')
	const css = await readFile('public/styles.css', 'utf8')
	const detailRowSource = appSource.slice(appSource.indexOf('function renderDetailEventRow('), appSource.indexOf('function renderDetailTargetControl('))
	const timelineItemSource = appSource.slice(appSource.indexOf('function renderTimelineItem('), appSource.indexOf('function renderTimelineIcon('))
	const clickSource = appSource.slice(appSource.indexOf("document.addEventListener('click'"), appSource.indexOf("document.addEventListener('toggle'"))

	assert.match(detailRowSource, /const timelineEventKey = detailTimelineEventKey\(event\)/)
	assert.match(detailRowSource, /data-timeline-event-key="\$\{timelineEventKey\}"/)
	assert.doesNotMatch(detailRowSource, /focusActionId \? '' : 'disabled'/)
	assert.match(clickSource, /if \(action === 'remove-timeline-event'\)/)
	assert.match(clickSource, /removeTimelineEvent\(target\.dataset\.timelineEventKey\)/)
	assert.match(appSource, /function removeTimelineEvent\(/)
	assert.match(appSource, /editableTimelineEventTargets\(eventKey\)/)
	assert.match(appSource, /removeEditableTimelineEvent\(target\.event\)/)
	assert.match(appSource, /function removeEditableTimelineEvent\(/)
	assert.match(appSource, /removeEventFromArray\(track\.qt,\s*event\)/)
	assert.match(appSource, /removeEventFromTimelineRows\(event\)/)
	assert.match(timelineItemSource, /renderTimelineDeleteButton\(item,\s*editableEvent\)/)
	assert.match(timelineItemSource, /renderTimelineDeleteButton\(item,\s*editable\)/)
	assert.match(appSource, /function renderTimelineDeleteButton\(/)
	assert.match(appSource, /class="timeline-delete-button manual-remove"/)
	assert.match(css, /\.timeline-delete-button\s*\{/)
	assert.match(css, /\.xiva-item\.editable:hover \.timeline-delete-button/s)
})

test('front-end uses an Apple Pro App inspired light design system', async () => {
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(css, /color-scheme:\s*light/)
	assert.match(css, /--bg:\s*#f5f5f7/)
	assert.match(css, /--text:\s*#1d1d1f/)
	assert.match(css, /--apple-blue:\s*#0071e3/)
	assert.match(css, /--button-shadow:\s*none/)
	assert.match(css, /body\s*\{[^}]*background:\s*var\(--bg\)/s)
	assert.match(css, /\.workspace,\s*\n\.inspector,\s*\n\.tool-panel\s*\{[^}]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.82\)/s)
	assert.match(css, /\.primary\s*\{[^}]*background:\s*var\(--apple-blue\)/s)
	assert.match(css, /\.xiva-shell\s*\{[^}]*background:\s*#fff/s)
	assert.match(css, /\.xiva-toolbar\s*\{[^}]*backdrop-filter:\s*blur\(20px\)/s)
})

test('topbar uses a compact dense toolbar to preserve editor space', async () => {
	const css = await readFile('public/styles.css', 'utf8')

	assert.match(css, /\.app-shell\s*\{[^}]*padding:\s*8px/s)
	assert.match(css, /\.workspace\s*\{[^}]*padding:\s*8px/s)
	assert.match(css, /\.topbar\s*\{[^}]*padding:\s*8px 10px/s)
	assert.match(css, /\.topbar-main\s*\{[^}]*display:\s*flex/s)
	assert.match(css, /\.topbar-main\s*\{[^}]*align-items:\s*center/s)
	assert.match(css, /\.topbar h2\s*\{[^}]*font-size:\s*16px/s)
	assert.match(css, /\.job-acr-status\s*\{[^}]*margin-top:\s*0/s)
	assert.match(css, /\.topbar-controls\s*\{[^}]*align-items:\s*center/s)
	assert.match(css, /\.topbar-controls label\s*\{[^}]*display:\s*flex/s)
	assert.match(css, /\.topbar-controls\s*\{[^}]*flex-wrap:\s*nowrap/s)
	assert.match(css, /\.topbar-controls \.ghost\s*\{[^}]*min-height:\s*30px/s)
	assert.match(css, /\.compact-rail\s*\{[^}]*flex-wrap:\s*nowrap/s)
	assert.match(css, /\.compact-share\s*\{[^}]*max-width:\s*180px/s)
	assert.match(css, /\.compact-share\s*\{[^}]*display:\s*none/s)
	assert.match(css, /\.compact-share \.eyebrow\s*\{[^}]*display:\s*none/s)
})
